exports_files([
    "guava_version.patch", 
    "macos_cp_reflink.patch", 
    "use_androidx.patch", 
    "androidx_annotation_template.patch",
    "databinding_deps.patch",
    "android_resource_processor_bazel_paths.patch",
    "allow_resource_conflicts.patch",
    "skip_library_resource_linking.patch",
    "fix_resource_priority_ordering.patch",
    "fix_aar_import_databinding_info.patch",
    "fix_databinding_providers.patch",
    "fix_databinding_data_binding.patch",
    "busybox_jvm_flags.patch",
    "fix_binary_r_class_generation.patch",
    "wire_strict_deps_flag.patch",
    "disable_aar_import_deps_checker.patch",
    "allow_deps_without_srcs.patch",
    "aar_import_export_r_java.patch",
    "connect_native_android_flags.patch",
    "native_databinding_package_info.patch",
    "databinding_non_transitive_r.patch",
    "databinding_non_transitive_r_impl.patch",
    "package_aware_rtxt_tool.patch",
    "package_aware_rtxt_merge_action.patch",
    "busybox_package_aware_rtxt.patch",
    "provider_package_aware_rtxt.patch",
    "binary_r_class_too_large_fix.patch",
    ]
)