exports_files([
    "android_resource_processor_bazel_paths.patch",
    "canonicalize_manifest_merger_log_paths.patch",
    "disable_instrumentation_min_sdk_floor.patch",
    "disable_instrumentation_mergee_manifests.patch",
    "fix_resource_priority_ordering.patch",
    "normalize_databinding_compiled_resources_timestamps.patch",
    "skip_instrumentation_min_sdk_validation.patch",
    "sort_resource_source_table.patch",
])
