exports_files([
    "skip_binary_r_jar_desugaring_attrs.patch",
    "skip_binary_r_jar_desugaring_flags.patch",
    "skip_binary_r_jar_desugaring_impl.patch",
    "skip_r_jar_desugaring.patch",
    "isolate_metadata_desugar_worker.patch",
    "normalize_desugar_zip_timestamps.patch",
    "normalize_desugar_missing_interface_origins.patch",
])
