name: Build workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v3

      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "bazel-cache"
          key: caches-${{ runner.os }}-release

      - name: Lint
        run: bazelisk run //:buildifier -- --mode=check -r $(pwd)

      - name: Build
        run: bazelisk build //...

      - name: Test
        run: bazelisk test //...